5219
After fixing bugs, checking alloc_ids now requires 9 instructions rather
than 6.

diff --git a/subx/test_apps b/subx/test_apps
--- a/subx/test_apps
+++ b/subx/test_apps
@@ -131,9 +131,13 @@ test `uname` = 'Linux'  &&  examples/ex12
 echo handle
 ./subx translate 0*.subx apps/handle.subx  -o apps/handle
 [ "$1" != record ]  &&  git diff --exit-code apps/handle
-./subx run apps/handle 2>&1  |grep -q 'lookup failed'
+./subx run apps/handle >& handle.out  ||  true
+grep -q 'lookup succeeded' handle.out  ||  { echo "missing success test"; exit 1; }
+grep -q 'lookup failed' handle.out  ||  { echo "missing failure test"; exit 1; }
 test `uname` = 'Linux'  &&  {
-  apps/handle test 2>&1  |grep -q 'lookup failed'
+  apps/handle >& handle.out  ||  true
+  grep -q 'lookup succeeded' handle.out  ||  { echo "missing success test"; exit 1; }
+  grep -q 'lookup failed' handle.out  ||  { echo "missing failure test"; exit 1; }
 }
 
 echo factorial
