inline SubX translation
We can't really translate purely SubX code anyway at the top-level. Stop
exposing those scripts.

diff --git a/translate_emulated b/translate_emulated
--- a/translate_emulated
+++ b/translate_emulated
@@ -7,6 +7,53 @@
 set -e
 set -v
 
-cat $* [0-9]*.mu  |linux/bootstrap/bootstrap run linux/mu                 > a.subx
+cat $* [0-9]*.mu                                          |linux/bootstrap/bootstrap run linux/mu                         > a.subx
 
-./translate_subx_emulated boot.subx font.subx mu-init.subx [0-9]*.subx a.subx
+cat boot.subx font.subx mu-init.subx [0-9]*.subx a.subx   |linux/bootstrap/bootstrap run linux/braces                     > a.braces
+
+cat a.braces                                              |linux/bootstrap/bootstrap run linux/calls                      > a.calls
+
+cat a.calls                                               |linux/bootstrap/bootstrap run linux/sigils                     > a.sigils
+
+cat a.sigils                                              |linux/bootstrap/bootstrap run linux/tests                      > a.tests
+
+# no assort since baremetal SubX doesn't have segments yet
+
+cat a.tests                                               |linux/bootstrap/bootstrap run linux/dquotes                    > a.dquotes
+
+cat a.dquotes                                             |linux/bootstrap/bootstrap run linux/pack                       > a.pack
+
+cat a.pack                                                |linux/bootstrap/bootstrap run linux/survey_baremetal > labels
+cat a.pack                                                |linux/bootstrap/bootstrap run linux/labels_baremetal   labels  > a.survey
+
+cat a.survey                                              |linux/bootstrap/bootstrap run linux/hex                        > a.bin
+
+# Create code.img containing a.bin
+dd if=/dev/zero of=code.img count=20160  # 20*16*63 512-byte sectors = almost 10MB
+dd if=a.bin of=code.img conv=notrunc
+
+if [ `stat --printf="%s" a.bin` -ge 492544 ]  # 15 tracks * 63 sectors per track * 512 bytes per sector (keep this sync'd with boot.subx)
+then
+  echo "a.bin won't all be loaded on boot"
+  exit 1
+fi
+
+if [ `stat --printf="%s" a.bin` -ge 492544 ]  # 15 tracks * 63 sectors per track * 512 bytes per sector
+then
+  echo "a.bin will overwrite BIOS/Video memory; you'll need to adjust boot.subx to load code to some other non-contiguous area of memory"
+  exit 1
+fi
+
+# Latter half of disk is for debug info.
+dd if=labels of=code.img seek=10080 conv=notrunc  # keep this sync'd with abort.subx
+if [ `stat --printf="%s" labels` -ge 1048576 ]  # 8 reads * 256 sectors * 512 bytes per sector
+then
+  echo "labels won't all be loaded on abort"
+  exit 1
+fi
+
+if [ `wc -l < labels` -gt 20480 ]  # 0x5000 stream capacity in abort.subx
+then
+  echo "abort will go into infinite regress"
+  exit 1
+fi
